Fix build scope OS detection in tools.microsoft.visual.VCVars (#15568)
* Fix build scope OS detection in tools.microsoft.visual.VCVars

Get the build scope OS type using the common subsystems API.
Do not assume that the host profile OS is the same as
the build profile OS and do not generate "conanvcvars.bat"
on Unix build systems.

The same method of build OS detection is already used in
tools.env.EnvVars to generate the appropriate virtual environment
script type and in tools.cmake.toolchain to write correct file paths.

This change makes cross-compilation from Linux to Windows work
when using MSVC compilers running natively on Linux.

The original cross-compilation failure looks like:

    ConanException: Cannot wrap command with different envs,['/build/Debug/generators/conanbuild.bat'] - ['/build/Debug/generators/conanbuild.sh']

and is caused by conanvcvars.bat script being generated unconditionally
and included into conanbuild.bat even when running on Linux.

* fix: Change the VCVars build OS detection method

Use `conanfile.settings_build.os` in place of `deduce_subsystem()`.

* test: Add an integration test for the VCVars build OS detection

Check that conanvcvars.bat is not created on Linux build systems.

---------

Co-authored-by: James <james@conan.io>