feature: Improve dependency-cycle error to show the cycle (#11519)
* Improve dependency-cycle error to show the cycle

Original message isn't help when diagnosing problems with a recipe...
Now it will print out all the X->Y dependencies that remain after the
irrelevant components have been eliminated.

Within that list will be the problematic cycle.

For example, as a test I introduced a cycle into my prototype VTK recipe,

I added:
self.cpp_info.components["vtksys"].requires.append("CommonDataModel")

The cycle would be:
vtksys -> CommonDataModel -> CommonCore -> vtksys

The message was a bit more verbose than that, but enough to be helpful:

ERROR: There is a dependency loop in 'self.cpp_info.components' requires:
   CommonTransforms requires CommonMath
   CommonDataModel requires CommonCore
   CommonMath requires CommonCore
   CommonCore requires vtksys
   CommonTransforms requires CommonCore
   CommonCore requires kwiml
   CommonDataModel requires CommonMath
   vtksys requires CommonDataModel
   CommonDataModel requires CommonTransforms
   CommonMath requires kissfft

* add test

Co-authored-by: memsharded <james@conan.io>